language: python
python:
  # Note: this Python version applies only to the CI environment.
  - 3.6

install:
  - pip install -U docker-compose
  - echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_USERNAME}" --password-stdin quay.io

env:
  global:
    - COMPOSE_FILE=docker-compose.ci.yml
    - DOCKER_REPO=quay.io/litheblas/mediawiki
    - DOCKER_REPO_BUILD_TAG=${DOCKER_REPO}:latest
    - DOCKER_REPO_SHA_TAG=${DOCKER_REPO}:sha-${TRAVIS_COMMIT}
    - DOCKER_REPO_BRANCH_TAG=${DOCKER_REPO}:${TRAVIS_BRANCH}

script:
  - docker-compose build

after_success:
  - docker tag ${DOCKER_REPO_BUILD_TAG} ${DOCKER_REPO_SHA_TAG}
  - docker tag ${DOCKER_REPO_BUILD_TAG} ${DOCKER_REPO_BRANCH_TAG}
  - docker push ${DOCKER_REPO_SHA_TAG}
  - docker push ${DOCKER_REPO_BRANCH_TAG}
